'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BoomVM_Veldin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property BoomVM_004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoomVM-004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Making script executable... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Add_Permision() As String
            Get
                Return ResourceManager.GetString("DP_Add_Permision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Changing directory to /root/boomvm... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Change_Directory() As String
            Get
                Return ResourceManager.GetString("DP_Change_Directory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Creating directory &quot;/root/boomvm&quot;... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Create_Directory() As String
            Get
                Return ResourceManager.GetString("DP_Create_Directory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Installation complete. Details appended below: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Done_Install() As String
            Get
                Return ResourceManager.GetString("DP_Done_Install", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Remove complete. Details appended below: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Done_Remove() As String
            Get
                Return ResourceManager.GetString("DP_Done_Remove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Update complete. Details appended below: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Done_Update() As String
            Get
                Return ResourceManager.GetString("DP_Done_Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Downloading Installation Script... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Download_Script() As String
            Get
                Return ResourceManager.GetString("DP_Download_Script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed:  的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Failed() As String
            Get
                Return ResourceManager.GetString("DP_Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Installing... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Install() As String
            Get
                Return ResourceManager.GetString("DP_Install", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Parameter cannot be empty. 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Param_Empty() As String
            Get
                Return ResourceManager.GetString("DP_Param_Empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Removing... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Remove() As String
            Get
                Return ResourceManager.GetString("DP_Remove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Connecting to SFTP Server... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_SFTP_Connect() As String
            Get
                Return ResourceManager.GetString("DP_SFTP_Connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Starting SFTP... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_SFTP_Start() As String
            Get
                Return ResourceManager.GetString("DP_SFTP_Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Connecting to SSH Server... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_SSH_Connect() As String
            Get
                Return ResourceManager.GetString("DP_SSH_Connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Starting SSH... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_SSH_Start() As String
            Get
                Return ResourceManager.GetString("DP_SSH_Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Success 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Success() As String
            Get
                Return ResourceManager.GetString("DP_Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Updating... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Update() As String
            Get
                Return ResourceManager.GetString("DP_Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Uploading script... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DP_Upload_Script() As String
            Get
                Return ResourceManager.GetString("DP_Upload_Script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property FUS_004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FUS-004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 This BOM file is invalid. 的本地化字符串。
        '''</summary>
        Public ReadOnly Property IO_Package_Invalid() As String
            Get
                Return ResourceManager.GetString("IO_Package_Invalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public ReadOnly Property MineServ_001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MineServ-001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Remove Server &apos; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Confirm_Remove_server() As String
            Get
                Return ResourceManager.GetString("UI_Confirm_Remove_server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Invalid Server Configuration 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Invalid_Server_From_Config() As String
            Get
                Return ResourceManager.GetString("UI_Invalid_Server_From_Config", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cannot load details.  的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Package_Detail_Load_Error() As String
            Get
                Return ResourceManager.GetString("UI_Package_Detail_Load_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add Source 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Add() As String
            Get
                Return ResourceManager.GetString("UI_Source_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Connecting to Source... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Connecting() As String
            Get
                Return ResourceManager.GetString("UI_Source_Connecting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Source Domain Not Found From Configuration File 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Domain_Not_Found() As String
            Get
                Return ResourceManager.GetString("UI_Source_Domain_Not_Found", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Done 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Done() As String
            Get
                Return ResourceManager.GetString("UI_Source_Done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error:  的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Error() As String
            Get
                Return ResourceManager.GetString("UI_Source_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Fetching Data ... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Fetch_Data() As String
            Get
                Return ResourceManager.GetString("UI_Source_Fetch_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Getting Source Domain... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Get_Domain() As String
            Get
                Return ResourceManager.GetString("UI_Source_Get_Domain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error: Package Information Not Found On This Source. 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Invalid_Source() As String
            Get
                Return ResourceManager.GetString("UI_Source_Invalid_Source", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Preparing Details... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Prepare_Detail() As String
            Get
                Return ResourceManager.GetString("UI_Source_Prepare_Detail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Resolving Source Information... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Resolving_Configuration() As String
            Get
                Return ResourceManager.GetString("UI_Source_Resolving_Configuration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 This source seems not be a valid source. 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Validate_Failed() As String
            Get
                Return ResourceManager.GetString("UI_Source_Validate_Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Validating... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_Source_Validating() As String
            Get
                Return ResourceManager.GetString("UI_Source_Validating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Not Selected 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UI_txtBOM_Default() As String
            Get
                Return ResourceManager.GetString("UI_txtBOM_Default", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
